### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by jolic** [Sneezoo/babel-7-jest#1]
Still get "Cannot find module '@babel/core'" when running jest.

Could you please provide a simple package.json of a running example?

**Comment by Sneezoo** [comment]
Hi @jolic,
`@babel/core` is a peerDependency, so lets try it with this package.json:
```json
{
  "name": "example",
  "version": "0.0.1",
  "description": "Example of jest and babel 7",
  "main": "server.js",
  "scripts": {
    "test": "jest",
    "dev:test": "jest --watch"
  },
  "jest": {
    "transform": {
      ".js$": "babel-7-jest"
    }
  },
  "author": "Sneezoo",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.31",
    "babel-7-jest": "^21.3.1",
    "jest": "^21.2.1"
  },
  "dependencies": {}
}
```
This should do it! Please tell me if you were able to make it work with this. Then I will add it to the README

**Comment by jolic** [comment]
Yes, this worked. Thank you!

**Comment by Sneezoo** [comment]
Added example package.json to README
