### ISSUE TITLE
ReferenceError: Unknown helper assertThisInitialized

### ISSUE THREAD

**Issue by darkowic** [Sneezoo/babel-7-jest#2]
Hello!

First: Great job!

I'm trying to run jest with babel 7 and I use the library. I'm encountering following error:

```
 FAIL  src/tests/some.test.jsx
  ● Test suite failed to run

    ReferenceError: Unknown helper assertThisInitialized
      
      at loadHelper (node_modules/babel-7-jest/node_modules/@babel/helpers/lib/index.js:239:40)
      at ThisExpression (node_modules/@babel/plugin-transform-classes/lib/vanilla.js:51:60)
```

My babel config:
```
  "babel": {
    "plugins": [
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-proposal-class-properties"
    ],
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "browsers": [
              "> 2% in DE",
              "safari>=9",
              "ie>=11"
            ]
          },
          "useBuiltIns": "usage",
          "modules": false
        }
      ],
      "@babel/preset-stage-0",
      "@babel/preset-react"
    ],
    "env": {
      "production": {
        "only": [
          "src"
        ],
        "plugins": [
          "babel-plugin-transform-react-remove-prop-types",
          "@babel/plugin-transform-react-constant-elements",
          "@babel/plugin-transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "@babel/plugin-transform-modules-commonjs",
          "babel-plugin-dynamic-import-node-babel-7",
          "@babel/syntax-export-extensions"
        ]
      }
    }
  },
```

Have no idea right now what is the problem. Any thoughts?

**Comment by Sneezoo** [comment]
Hi,

thanks!

I found this pull request: https://github.com/babel/babel/pull/6467/files
So I assume _assertThisInitialized_ was not implemented until v7.0.0-beta.35
Maybe you just need to update your `@babel` dependency.
I hope that helps!

**Comment by darkowic** [comment]
Hmm actually I'm using `beta.37`. Will check it tomorrow again.

**Comment by darkowic** [comment]
I checked and all my dependencies are in version 37. I answer in babel issue

**Comment by darkowic** [comment]
Looks like a newer version of babel dependencies are not installed correctly - babel-7-jest is using his own `node_modules` with babel in version beta.31. Question, why?

**Comment by darkowic** [comment]
Do we even need the `npm-shrinkwrap.json` if we are using `^` in dependencies? I download locally your project and run it with newer babel version - now it works.

**Comment by darkowic** [comment]
I've install the newest version of jest as they suggest in documentation - https://facebook.github.io/jest/docs/en/getting-started.html#using-babel and everything is working. Looks like this package is not needed anymore :) Thank you!
